server:
  port: 9000

spring:
  application:
    name: producer-app
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  kafka:
    topicName: second_topic
